"""Render /etc/bedrock/daemon.toml and start bedrock-rust.

Invoked from `mgmt_install.install_full` (the first node) and
`agent_install.install` (each joining node). The TOML file describes
exactly how the bedrock-rust daemon is to run on this node — log
location, IPC socket, peer addresses, witness endpoints, identifiers,
TTL/heartbeat knobs.
"""

from __future__ import annotations

import secrets
import subprocess
from pathlib import Path
from typing import Iterable

DAEMON_CONFIG = Path("/etc/bedrock/daemon.toml")
CLUSTER_KEY = Path("/etc/bedrock/cluster.key")


def write_cluster_key(material: bytes | None = None) -> bytes:
    """Write the cluster's 32-byte AEAD key. Idempotent — preserves an
    existing key. Returns the key bytes (so the master can replicate
    it to peers)."""
    if CLUSTER_KEY.exists():
        return CLUSTER_KEY.read_bytes()
    CLUSTER_KEY.parent.mkdir(parents=True, exist_ok=True)
    key = material or secrets.token_bytes(32)
    if len(key) != 32:
        raise ValueError("cluster key must be 32 bytes")
    CLUSTER_KEY.write_bytes(key)
    CLUSTER_KEY.chmod(0o600)
    return key


def render_daemon_toml(
    *,
    sender_id: int,
    peer_sender_ids: Iterable[int] = (),
    peer_listen: Iterable[str],
    peer: Iterable[str],
    fence_interfaces: Iterable[str],
    witnesses: Iterable[dict],
    role: str = "standalone",
    lease_ttl_ms: int = 5_000,
    heartbeat_ms: int = 1_000,
    peer_in_maintenance: bool = False,
) -> None:
    """Write /etc/bedrock/daemon.toml. `witnesses` is an iterable of
    {id, host, port, pubkey_hex} dicts.

    `peer_sender_ids` is every OTHER node's sender_id (any order; the
    Rust election only uses len() for the vote total and membership
    for the smaller-id-priority check)."""
    DAEMON_CONFIG.parent.mkdir(parents=True, exist_ok=True)

    psids = list(peer_sender_ids)
    lines = [
        "# Generated by bedrock; rebuilt deterministically from the snapshot.",
        # log_dir removed in post-alpha rewrite (D-22): bedrock-rust
        # no longer carries a log; rqlite owns cluster state.
        f'ipc_sock = "/run/bedrock-rust.sock"',
        f'sender_id = {sender_id}',
    ]
    if psids:
        lines.append(f'peer_sender_ids = [{", ".join(str(s) for s in psids)}]')
    lines += [
        f'lease_ttl_ms = {lease_ttl_ms}',
        f'heartbeat_ms = {heartbeat_ms}',
        f'role = "{role}"',
        f'cluster_key_file = "{CLUSTER_KEY}"',
    ]
    if peer_in_maintenance:
        lines.append(f'peer_in_maintenance = true')
    pl = list(peer_listen)
    if pl:
        lines.append("peer_listen = " + _toml_str_list(pl))
    pp = list(peer)
    if pp:
        lines.append("peer = " + _toml_str_list(pp))
    fi = list(fence_interfaces)
    if fi:
        lines.append("fence_interfaces = " + _toml_str_list(fi))
    for w in witnesses:
        lines += [
            "",
            "[[witness]]",
            f'id = "{w["id"]}"',
            f'host = "{w["host"]}"',
            f'port = {int(w.get("port", 12321))}',
            f'pubkey_hex = "{w["pubkey_hex"]}"',
        ]
    lines.append("")
    DAEMON_CONFIG.write_text("\n".join(lines))
    DAEMON_CONFIG.chmod(0o640)


def _toml_str_list(xs: list[str]) -> str:
    return "[" + ", ".join(f'"{x}"' for x in xs) + "]"


def render_from_snapshot(snapshot: dict, this_node: str,
                          fence_interfaces=None,
                          lease_ttl_ms: int = 5_000,
                          heartbeat_ms: int = 1_000) -> None:
    """Regenerate /etc/bedrock/daemon.toml as a deterministic projection
    of the cluster's materialised snapshot (the view_builder.fold output).

    The snapshot is the source of truth; daemon.toml is an output that
    can be regenerated at any time from a snapshot. Callers are:
      - mgmt_install / agent_install at first install
      - `bedrock witness add` / `rm` after the log entry replicates
      - any future operation that mutates anything daemon.toml depends on

    Picks roles based on snapshot["mgmt_master"] (master = leader,
    others = follower). Picks sender_ids by index into the sorted
    nodes map (deterministic across nodes — same algorithm runs on
    every node's view_builder, so every regenerated daemon.toml
    agrees on who's sender_id 1, 2, 3…).
    """
    nodes = snapshot.get("nodes", {})
    name_list = sorted(nodes.keys())   # deterministic order

    # Bail out on a bootstrap-empty snapshot. This happens to a freshly
    # joined follower whose log hasn't replicated yet: the orchestrator
    # subscriber on the joiner fires render_from_snapshot before the
    # leader has shipped any entries, so `nodes` is empty and `master`
    # is None. The previous behaviour (re-render with `peer=[]` +
    # `role=leader`) hard-bricked replication: bedrock-rust restarted
    # as a standalone leader, stopped dialing the master, and the log
    # never caught up. Preserving the agent_install bootstrap toml
    # until *some* membership entry has replicated is correct: the
    # next subscriber tick after the first NODE_REGISTER arrives will
    # produce a populated snapshot and a real config.
    if not name_list or this_node not in name_list:
        return

    my_idx = name_list.index(this_node) + 1
    # All other nodes' sender_ids → peer_sender_ids list. The Rust
    # weighted-vote election counts these (10 votes per node + 1 for
    # witness) to decide quorum at N≥3. Empty for standalone.
    #
    # Peer dial address — preference order:
    #   1. loopback_ip — the mesh cluster identity. The kernel route
    #      to this /32 picks the best physical NIC via bedrock-net's
    #      metric-ordered routing, so bedrock-rust gets multi-path
    #      failover for free without knowing about it.
    #   2. drbd_ip — the dedicated peer-link at N≥2 in legacy
    #      deployments (separate cable, redundant). Kept for clusters
    #      that pre-date the mesh layer.
    #   3. host — the mgmt LAN. The always-true fallback.
    # Without these fallbacks (especially loopback_ip when present),
    # bedrock-rust would dial a single fixed address and lose
    # multi-path resilience entirely.
    peer_addrs: list[str] = []
    peer_sender_ids: list[int] = []
    for nm in name_list:
        if nm == this_node:
            continue
        n = nodes[nm]
        addr = (n.get("loopback_ip")
                or n.get("drbd_ip")
                or n.get("host", ""))
        if addr:
            peer_addrs.append(f"{addr}:8200")
        peer_sender_ids.append(name_list.index(nm) + 1)

    witnesses = []
    for wid, w in (snapshot.get("witnesses") or {}).items():
        addr = w.get("addr", "")
        if ":" in addr:
            host, _, port_s = addr.rpartition(":")
            port = int(port_s) if port_s.isdigit() else 12321
        else:
            host, port = addr, 12321
        witnesses.append({
            "id": wid,
            "host": host,
            "port": port,
            "pubkey_hex": w.get("witness_pubkey", ""),
        })

    # Role: master ⇒ leader, anyone else ⇒ follower. master=None can't
    # happen here — the early-return above guarantees this_node is in
    # the snapshot, which only occurs after at least one MGMT_MASTER
    # entry has folded into the view. (If master truly is missing
    # despite a populated nodes map, treat ourselves as follower so we
    # keep dialing peers instead of going silent as a phantom leader.)
    master = snapshot.get("mgmt_master")
    role = "leader" if master == this_node else "follower"

    # Peer-in-maintenance: when our peer node has maintenance=true in
    # the snapshot, the daemon treats peer silence as expected — we
    # keep running solo without witness-arbitration. v0.1 single-peer
    # case: any peer in maintenance flips this. (Multi-peer at N>=3
    # would need a quorum-aware version.)
    peer_in_maint = False
    for nm in name_list:
        if nm == this_node:
            continue
        if (nodes.get(nm) or {}).get("maintenance"):
            peer_in_maint = True
            break

    render_daemon_toml(
        sender_id=my_idx,
        peer_sender_ids=peer_sender_ids,
        peer_listen=["0.0.0.0:8200"],
        peer=peer_addrs,
        fence_interfaces=fence_interfaces or [],
        witnesses=witnesses,
        role=role,
        lease_ttl_ms=lease_ttl_ms,
        heartbeat_ms=heartbeat_ms,
        peer_in_maintenance=peer_in_maint,
    )


def restart() -> None:
    """systemctl daemon-reload + restart bedrock-rust. Idempotent.
    The mgmt service's orchestrator (mgmt/orchestrator.py) drives the
    rest of the per-node lifecycle — folding the log into daemon.toml
    and triggering this very function when the toml changes."""
    subprocess.run(["systemctl", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "enable", "--now", "bedrock-rust.service"],
                   check=False, capture_output=True)
    subprocess.run(["systemctl", "restart", "bedrock-rust.service"],
                   check=False, capture_output=True)


def init_log_if_needed(cluster_uuid: str) -> None:
    """Post-rewrite: no-op. bedrock-rust no longer maintains a
    hash-chained log (post-alpha rewrite D-22); rqlite owns
    cluster state. Kept as a callable so mgmt_install's older
    call site doesn't break — delete the call once mgmt_install
    is updated."""
    return
