"""Render /etc/bedrock/daemon.toml and start bedrock-rust.

Invoked from `mgmt_install.install_full` (the first node) and
`agent_install.install` (each joining node). The TOML file describes
exactly how the bedrock-rust daemon is to run on this node — log
location, IPC socket, peer addresses, witness endpoints, identifiers,
TTL/heartbeat knobs.
"""

from __future__ import annotations

import secrets
import subprocess
from pathlib import Path
from typing import Iterable

DAEMON_CONFIG = Path("/etc/bedrock/daemon.toml")
CLUSTER_KEY = Path("/etc/bedrock/cluster.key")


def write_cluster_key(material: bytes | None = None) -> bytes:
    """Write the cluster's 32-byte AEAD key. Idempotent — preserves an
    existing key. Returns the key bytes (so the master can replicate
    it to peers)."""
    if CLUSTER_KEY.exists():
        return CLUSTER_KEY.read_bytes()
    CLUSTER_KEY.parent.mkdir(parents=True, exist_ok=True)
    key = material or secrets.token_bytes(32)
    if len(key) != 32:
        raise ValueError("cluster key must be 32 bytes")
    CLUSTER_KEY.write_bytes(key)
    CLUSTER_KEY.chmod(0o600)
    return key


def render_daemon_toml(
    *,
    sender_id: int,
    peer_sender_id: int | None,
    peer_listen: Iterable[str],
    peer: Iterable[str],
    fence_interfaces: Iterable[str],
    witnesses: Iterable[dict],
    role: str = "standalone",
    lease_ttl_ms: int = 5_000,
    heartbeat_ms: int = 1_000,
) -> None:
    """Write /etc/bedrock/daemon.toml. `witnesses` is an iterable of
    {id, host, port, pubkey_hex} dicts."""
    DAEMON_CONFIG.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated by bedrock; edit cluster.json + run `bedrock init/join` to regenerate.",
        f'log_dir = "/var/lib/bedrock/log"',
        f'ipc_sock = "/run/bedrock-rust.sock"',
        f'sender_id = {sender_id}',
    ]
    if peer_sender_id is not None:
        lines.append(f'peer_sender_id = {peer_sender_id}')
    lines += [
        f'lease_ttl_ms = {lease_ttl_ms}',
        f'heartbeat_ms = {heartbeat_ms}',
        f'role = "{role}"',
        f'cluster_key_file = "{CLUSTER_KEY}"',
    ]
    pl = list(peer_listen)
    if pl:
        lines.append("peer_listen = " + _toml_str_list(pl))
    pp = list(peer)
    if pp:
        lines.append("peer = " + _toml_str_list(pp))
    fi = list(fence_interfaces)
    if fi:
        lines.append("fence_interfaces = " + _toml_str_list(fi))
    for w in witnesses:
        lines += [
            "",
            "[[witness]]",
            f'id = "{w["id"]}"',
            f'host = "{w["host"]}"',
            f'port = {int(w.get("port", 12321))}',
            f'pubkey_hex = "{w["pubkey_hex"]}"',
        ]
    lines.append("")
    DAEMON_CONFIG.write_text("\n".join(lines))
    DAEMON_CONFIG.chmod(0o640)


def _toml_str_list(xs: list[str]) -> str:
    return "[" + ", ".join(f'"{x}"' for x in xs) + "]"


def restart() -> None:
    """systemctl restart bedrock-rust. Idempotent — fine if it was stopped."""
    subprocess.run(["systemctl", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "enable", "--now", "bedrock-rust.service"],
                   check=False, capture_output=True)
    subprocess.run(["systemctl", "restart", "bedrock-rust.service"],
                   check=False, capture_output=True)


def init_log_if_needed(cluster_uuid: str) -> None:
    """Run `bedrock-rust log init --cluster-uuid <uuid>` if the log
    doesn't already exist on this node."""
    seg = Path("/var/lib/bedrock/log/00000001.log")
    if seg.exists():
        return
    subprocess.check_call([
        "/usr/local/bin/bedrock-rust",
        "--log-dir", "/var/lib/bedrock/log",
        "log", "init",
        "--cluster-uuid", cluster_uuid,
    ])
