"""Render /etc/bedrock/daemon.toml and start bedrock-rust.

Invoked from `mgmt_install.install_full` (the first node) and
`agent_install.install` (each joining node). The TOML file describes
exactly how the bedrock-rust daemon is to run on this node — log
location, IPC socket, peer addresses, witness endpoints, identifiers,
TTL/heartbeat knobs.
"""

from __future__ import annotations

import secrets
import subprocess
from pathlib import Path
from typing import Iterable

DAEMON_CONFIG = Path("/etc/bedrock/daemon.toml")
CLUSTER_KEY = Path("/etc/bedrock/cluster.key")


def write_cluster_key(material: bytes | None = None) -> bytes:
    """Write the cluster's 32-byte AEAD key. Idempotent — preserves an
    existing key. Returns the key bytes (so the master can replicate
    it to peers)."""
    if CLUSTER_KEY.exists():
        return CLUSTER_KEY.read_bytes()
    CLUSTER_KEY.parent.mkdir(parents=True, exist_ok=True)
    key = material or secrets.token_bytes(32)
    if len(key) != 32:
        raise ValueError("cluster key must be 32 bytes")
    CLUSTER_KEY.write_bytes(key)
    CLUSTER_KEY.chmod(0o600)
    return key


def render_daemon_toml(
    *,
    sender_id: int,
    peer_sender_id: int | None = None,
    peer_sender_ids: Iterable[int] = (),
    peer_listen: Iterable[str],
    peer: Iterable[str],
    fence_interfaces: Iterable[str],
    witnesses: Iterable[dict],
    role: str = "standalone",
    lease_ttl_ms: int = 5_000,
    heartbeat_ms: int = 1_000,
    peer_in_maintenance: bool = False,
) -> None:
    """Write /etc/bedrock/daemon.toml. `witnesses` is an iterable of
    {id, host, port, pubkey_hex} dicts.

    `peer_sender_ids` is the canonical N-peer surface (every other
    node's sender_id, in any order). `peer_sender_id` is the legacy
    single-peer alias kept so dev `bedrock-rust daemon --peer-sender-id`
    invocations still work."""
    DAEMON_CONFIG.parent.mkdir(parents=True, exist_ok=True)

    psids = list(peer_sender_ids)
    if not psids and peer_sender_id is not None:
        psids = [peer_sender_id]

    lines = [
        "# Generated by bedrock; rebuilt deterministically from the snapshot.",
        f'log_dir = "/var/lib/bedrock/log"',
        f'ipc_sock = "/run/bedrock-rust.sock"',
        f'sender_id = {sender_id}',
    ]
    if psids:
        lines.append(f'peer_sender_ids = [{", ".join(str(s) for s in psids)}]')
    lines += [
        f'lease_ttl_ms = {lease_ttl_ms}',
        f'heartbeat_ms = {heartbeat_ms}',
        f'role = "{role}"',
        f'cluster_key_file = "{CLUSTER_KEY}"',
    ]
    if peer_in_maintenance:
        lines.append(f'peer_in_maintenance = true')
    pl = list(peer_listen)
    if pl:
        lines.append("peer_listen = " + _toml_str_list(pl))
    pp = list(peer)
    if pp:
        lines.append("peer = " + _toml_str_list(pp))
    fi = list(fence_interfaces)
    if fi:
        lines.append("fence_interfaces = " + _toml_str_list(fi))
    for w in witnesses:
        lines += [
            "",
            "[[witness]]",
            f'id = "{w["id"]}"',
            f'host = "{w["host"]}"',
            f'port = {int(w.get("port", 12321))}',
            f'pubkey_hex = "{w["pubkey_hex"]}"',
        ]
    lines.append("")
    DAEMON_CONFIG.write_text("\n".join(lines))
    DAEMON_CONFIG.chmod(0o640)


def _toml_str_list(xs: list[str]) -> str:
    return "[" + ", ".join(f'"{x}"' for x in xs) + "]"


def render_from_snapshot(snapshot: dict, this_node: str,
                          fence_interfaces=None,
                          lease_ttl_ms: int = 5_000,
                          heartbeat_ms: int = 1_000) -> None:
    """Regenerate /etc/bedrock/daemon.toml as a deterministic projection
    of the cluster's materialised snapshot (the view_builder.fold output).

    The snapshot is the source of truth; daemon.toml is an output that
    can be regenerated at any time from a snapshot. Callers are:
      - mgmt_install / agent_install at first install
      - `bedrock witness add` / `rm` after the log entry replicates
      - any future operation that mutates anything daemon.toml depends on

    Picks roles based on snapshot["mgmt_master"] (master = leader,
    others = follower). Picks sender_ids by index into the sorted
    nodes map (deterministic across nodes — same algorithm runs on
    every node's view_builder, so every regenerated daemon.toml
    agrees on who's sender_id 1, 2, 3…).
    """
    nodes = snapshot.get("nodes", {})
    name_list = sorted(nodes.keys())   # deterministic order

    if this_node in name_list:
        my_idx = name_list.index(this_node) + 1
    else:
        my_idx = 1
    # All other nodes' sender_ids → peer_sender_ids list. The Rust
    # weighted-vote election counts these (10 votes per node + 1 for
    # witness) to decide quorum at N≥3. Empty for standalone.
    peers_drbd = []
    peer_sender_ids: list[int] = []
    for nm in name_list:
        if nm == this_node:
            continue
        n = nodes[nm]
        if n.get("drbd_ip"):
            peers_drbd.append(f"{n['drbd_ip']}:8200")
        peer_sender_ids.append(name_list.index(nm) + 1)

    witnesses = []
    for wid, w in (snapshot.get("witnesses") or {}).items():
        addr = w.get("addr", "")
        if ":" in addr:
            host, _, port_s = addr.rpartition(":")
            port = int(port_s) if port_s.isdigit() else 12321
        else:
            host, port = addr, 12321
        witnesses.append({
            "id": wid,
            "host": host,
            "port": port,
            "pubkey_hex": w.get("witness_pubkey", ""),
        })

    master = snapshot.get("mgmt_master")
    role = "leader" if master == this_node or master is None else "follower"

    # Peer-in-maintenance: when our peer node has maintenance=true in
    # the snapshot, the daemon treats peer silence as expected — we
    # keep running solo without witness-arbitration. v0.1 single-peer
    # case: any peer in maintenance flips this. (Multi-peer at N>=3
    # would need a quorum-aware version.)
    peer_in_maint = False
    for nm in name_list:
        if nm == this_node:
            continue
        if (nodes.get(nm) or {}).get("maintenance"):
            peer_in_maint = True
            break

    render_daemon_toml(
        sender_id=my_idx,
        peer_sender_ids=peer_sender_ids,
        peer_listen=["0.0.0.0:8200"],
        peer=peers_drbd,
        fence_interfaces=fence_interfaces or [],
        witnesses=witnesses,
        role=role,
        lease_ttl_ms=lease_ttl_ms,
        heartbeat_ms=heartbeat_ms,
        peer_in_maintenance=peer_in_maint,
    )


def restart() -> None:
    """systemctl restart bedrock-rust + ensure bedrock-watcher is up.
    Idempotent — fine if either was stopped."""
    subprocess.run(["systemctl", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "enable", "--now", "bedrock-rust.service"],
                   check=False, capture_output=True)
    subprocess.run(["systemctl", "restart", "bedrock-rust.service"],
                   check=False, capture_output=True)
    # The watcher polls IPC to regen daemon.toml on log change. It's
    # the per-node side of "log-driven config propagation" (no SSH).
    subprocess.run(["systemctl", "enable", "--now", "bedrock-watcher.service"],
                   check=False, capture_output=True)


def init_log_if_needed(cluster_uuid: str) -> None:
    """Run `bedrock-rust log init --cluster-uuid <uuid>` if the log
    doesn't already exist on this node."""
    seg = Path("/var/lib/bedrock/log/00000001.log")
    if seg.exists():
        return
    subprocess.check_call([
        "/usr/local/bin/bedrock-rust",
        "--log-dir", "/var/lib/bedrock/log",
        "log", "init",
        "--cluster-uuid", cluster_uuid,
    ])
